### ISSUE TITLE
Wrong data shown in infrastructure service and secrets lists

### ISSUE THREAD

**Issue by mnonnenmacher** [eclipse-apoapsis/ort-server#812] opened 2024-08-14 09:07 UTC
In the organization view, when clicking on "Secrets" and then very quickly on "Infrastructure Services" it can happen that the infrastructure service list contains the secrets. The same issue can happen the other way round.

![image](https://github.com/user-attachments/assets/1e9952ef-3784-4568-bece-b9428ff446ea)

**Comment by mmurto** [comment] 2024-08-14 13:28
This is caused by invalid query keys at least in https://github.com/eclipse-apoapsis/ort-server/blob/f38596d5129119bacc5151e87f6a71d2744ed0d8/ui/src/routes/_layout/organizations/%24orgId/infrastructure-services/index.tsx#L148 and https://github.com/eclipse-apoapsis/ort-server/blob/f38596d5129119bacc5151e87f6a71d2744ed0d8/ui/src/routes/_layout/organizations/%24orgId/secrets/index.tsx#L171.

They should be a variable ending with `Key` - the currently variables point to functions instead of strings, which lead to `null` being used in the query key, which leads to them sharing the same cache. This causes the previous cache to be displayed before the new refresh request is finished.

**Comment by Etsija** [comment] 2024-08-15 08:23
Fixed with #819.

**Closed by Etsija** 2024-08-15 08:23 UTC
Labels: bug, ui
