### ISSUE TITLE
Flakiness in Build and Test / test action

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#720] opened 2024-07-22 08:48 UTC
Lately (at least for a few weeks now) there's been some flakiness in the GitHub test action when doing PRs, despite no code changes to the back-end (only front-end code changes).  Quite often need to rerun the test action, which slows down reviewing and merging PRs.  The test logs haven't so far shown any specific reasons to the failures.

**Comment by sschuberth** [comment] 2024-07-22 13:00
I've seen the SQS transport test to be flaky, but I could not reproduce it locally.

**Comment by mmurto** [comment] 2024-09-11 10:38
This doesn't seem to be fixed yet, the test job is still very flaky, which at least I find quite annoying.

**Comment by sschuberth** [comment] 2024-09-11 10:43
I believe it *was* better for a while, but reappeared. Let me simply try with increasing the timeout further.

**Comment by sschuberth** [comment] 2024-09-11 10:52
Hmm, given that the timeout is already at 30s, I wonder whether we should tweak some of these queue properties instead:

https://github.com/eclipse-apoapsis/ort-server/blob/10d58322e17d4767370d1062a175e6487572abf5/transport/sqs/src/main/kotlin/SqsMessageReceiverFactory.kt#L70-L82

**Comment by mnonnenmacher** [comment] 2024-12-14 18:01
I am closing this again as tests have been more stable recently.

**Closed by mnonnenmacher** 2024-12-14 18:01 UTC
Labels: bug, ci
